server:
  port: 9697

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:8989/eureka/

spring:
  application:
    name: client
  cloud:
    loadbalancer:
      retry:
        enabled: false